Tidal.GoogleMaps/Models/ErrorViewModel.cs
using System;

namespace Tidal.GoogleMaps.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Tidal.GoogleMaps/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Tidal.GoogleMaps.Models;

namespace Tidal.GoogleMaps.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Tidal.GoogleMaps/Controllers/MapController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Tidal.GoogleMaps.Contracts.Contracts;
using Tidal.GoogleMaps.Models.dto;

namespace Tidal.GoogleMaps.Controllers
{
    public class MapController : Controller
    {
        private readonly IMapService _mapService;

        public MapController(IMapService mapService)
        {
            _mapService = mapService;
        }
        public async Task<IActionResult> AddMarker(string name, string description, string lat, string lng)
        {
            var mapDto = new CreateUpdateMarkerDto
            {
                Description = description,
                Latitude = lat,
                Longitude = lng,
                Name = name
            };
            var newMarker = await _mapService.AddNewMarker(mapDto);
            return Json("");
        }

        public async Task<IActionResult> GetAllMarkers()
        {
            var maps = await _mapService.GetAllMarkers();
            return Json(maps);
        }
    }
}

Tidal.GoogleMaps/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_N1k4WKCdiZqCIjjgO0aaKz1Y19JqYqw"></script>
<script src="https://maps.googleapis.com/maps/api/js?AIzaSyD_N1k4WKCdiZqCIjjgO0aaKz1Y19JqYqw"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<div id="myDiv" style="width:100%;height:400px;"></div>

<script type="text/javascript">
    var infowindow = null;
    $.ajax({
        url: '@Url.Action("GetAllMarkers", "Map")',
        contentType: "application/json; charset=utf-8",
        dataType: "json",
        success: (data) => {
            //create a blank array
            var markers = [];

            //loop the list of addresses returned from Ajax request
            $.each(data,
                function(index, item) {
                    //create a blank array of address
                    var marker = {};
                    //fill data
                    marker["title"] = item.name;
                    marker["lat"] = item.latitude;
                    marker["lng"] = item.longitude;
                    marker["description"] = item.description;
                    //push the current marker details in markers array
                    markers.push(marker);
                });
            console.log(markers);
            DisplayGoogleMap(markers);
        },
        error: () => {

        }
    });


    function DisplayGoogleMap(markers = null) {


        //Set the Latitude and Longitude of the Map
        var myAddress = new google.maps.LatLng(24.466807, 54.384297);

        //Create Options or set different Characteristics of Google Map
        var mapOptions = {
            center: myAddress,
            zoom: 15,
            minZoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };

        //Display the Google map in the div control with the defined Options
        var map = new google.maps.Map(document.getElementById("myDiv"), mapOptions);

        //loop through each marker data
        for (i = 0; i < markers.length; i++) {
            var data = markers[i]
            //set lat long of current marker
            var myLatlng = new google.maps.LatLng(data.lat, data.lng);

            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: data.title
            });

            (function (marker, data) {
                // add a on marker click event
                google.maps.event.addListener(marker, "click", function (e) {
                    if (infowindow) {
                        infowindow.close();
                    }
                    //show description
                    infowindow = new google.maps.InfoWindow({
                        content: `${data.title} - ${data.description}`
                    });
                    infowindow.open(map, marker);
                });
            })(marker, data);
        }

        new google.maps.event.addListener(map, 'click', function (event) {
            if (infowindow) {
                infowindow.close();
            }
            placeMarker(map, event.latLng);
        });

        function placeMarker(map, location) {
            var marker = new google.maps.Marker({
                position: location,
                map: map
            });
            infowindow = new google.maps.InfoWindow({
                content: '</div><input class="form-control" placeholder="please enter name" type="text" id="name"/>' +
                    '<input class="form-control" type="text" placeholder="please enter description" id="description"/>' +
                    '<input type="button" class="primary-btn" id="SaveBtn" value="Submit"/>'+
                    '</div>'
            });
            infowindow.open(map, marker);
            isGoogleDomReady(infowindow, location);
        }
        function isGoogleDomReady(infowindow, location){
            google.maps.event.addListener(infowindow, 'domready', function () {
                $('#SaveBtn').on('click', function() {
                    let name = $('#name').val();
                    let description = $('#description').val();
                    let lat = location.lat();
                    let lng = location.lng();
                    $.ajax({
                        url: '@Url.Action("AddMarker", "Map")',
                        contentType: "application/json; charset=utf-8",
                        data: { name: name, description: description, lat: lat , lng : lng },
                        dataType: "json",
                        success: () => {
                            infowindow.close();
                        },
                        error: () => {

                        }
                    });
                });
            });
        }
    }
</script>

Tidal.GoogleMaps/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tidal.GoogleMaps</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tidal.GoogleMaps</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Tidal.GoogleMaps - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>